---
- name: Temporary directory
  ansible.builtin.file:
    path: "{{ linuxbrew_install_tmp }}"
    state: directory
    mode: 0700
  become: false

- name: Download Homebrew install script
  ansible.builtin.get_url:
    url: "{{ linuxbrew_install_url }}"
    dest: "{{ linuxbrew_install_tmp }}/install.sh"
    checksum: "{{ linuxbrew_install_checksum | default(omit) }}"
    mode: 0700
  become: false

- name: Install Homebrew with the installer
  ansible.builtin.command: sh -c "NONINTERACTIVE=1 {{ linuxbrew_install_tmp }}/install.sh"
  register: install_result
  changed_when: "install_result.rc == 0"
  become: false

- name: Remove temporary directory
  ansible.builtin.file:
    path: "{{ linuxbrew_install_tmp }}"
    state: absent
  become: false
